// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aq5fRtGWyO0YjnVVjmIJ3uMq-Sn4Srk',
    appId: '1:19090655500:android:7c3397f8ecb19be82de129',
    messagingSenderId: '19090655500',
    projectId: 'gendo-a3592',
    storageBucket: 'gendo-a3592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4O27m7SAfGn4XxM5rex5awjAmNxpV7ko',
    appId: '1:19090655500:ios:394a88d8d50eaf2c2de129',
    messagingSenderId: '19090655500',
    projectId: 'gendo-a3592',
    storageBucket: 'gendo-a3592.firebasestorage.app',
    iosBundleId: 'com.example.gendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4O27m7SAfGn4XxM5rex5awjAmNxpV7ko',
    appId: '1:19090655500:ios:394a88d8d50eaf2c2de129',
    messagingSenderId: '19090655500',
    projectId: 'gendo-a3592',
    storageBucket: 'gendo-a3592.firebasestorage.app',
    iosBundleId: 'com.example.gendo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMxxTXyu6MeJ_NM7fM5AiYb_kivmgaSYc',
    appId: '1:19090655500:web:22859dd93c54ef292de129',
    messagingSenderId: '19090655500',
    projectId: 'gendo-a3592',
    authDomain: 'gendo-a3592.firebaseapp.com',
    storageBucket: 'gendo-a3592.firebasestorage.app',
    measurementId: 'G-NP2VHVFT6E',
  );
}
